import React from 'react';
import { View, Text, StyleSheet, ImageBackground, Dimensions } from 'react-native';
import { colors } from '../theme/colors';

// Use the new ATM-style premium certificate image generated by AI
const TEMPLATE_IMAGE = require('../../assets/premium_atm_certificate.png');

interface DynamicCertificateProps {
    projectName: string;
    amount: number;
    date: string;
    assetId: string;
    ownerAddress: string;
}

export const DynamicCertificate: React.FC<DynamicCertificateProps> = ({
    projectName,
    amount,
    date,
    assetId,
    ownerAddress,
}) => {
    // Format addresses for clean display
    const shortOwner = ownerAddress ? `${ownerAddress.slice(0, 4)}...${ownerAddress.slice(-4)}` : 'UNKNOWN';
    const shortAsset = assetId ? `${assetId.slice(0, 8)}...${assetId.slice(-8)}` : 'PENDING MINT';

    return (
        <View style={styles.container}>
            <ImageBackground
                source={TEMPLATE_IMAGE}
                style={styles.cardBg}
                imageStyle={styles.cardImage}
            >
                {/* Branding / Header */}
                <View style={styles.header}>
                    <Text style={styles.brandText}>SOLCARBON</Text>
                    <Text style={styles.cardType}>CARBON CREDIT CARD</Text>
                </View>

                {/* EMV Chip Mock / Icon */}
                <View style={styles.chipWrapper}>
                    <View style={styles.chip} />
                </View>

                {/* Main Content Area */}
                <View style={styles.content}>
                    <Text style={styles.assetIdText}>{shortAsset}</Text>

                    <View style={styles.projectInfo}>
                        <Text style={styles.label}>ALLOCATION</Text>
                        <Text style={styles.valueLarge}>{amount.toFixed(2)} CC</Text>
                        <Text style={styles.projectName}>{projectName}</Text>
                    </View>
                </View>

                {/* Footer Area */}
                <View style={styles.footer}>
                    <View style={styles.footerBlock}>
                        <Text style={styles.label}>HOLDER</Text>
                        <Text style={styles.valueSmall}>{shortOwner}</Text>
                    </View>
                    <View style={styles.footerBlockRight}>
                        <Text style={styles.label}>DATE ISSUED</Text>
                        <Text style={styles.valueSmall}>{date}</Text>
                    </View>
                </View>
            </ImageBackground>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        width: '100%',
        aspectRatio: 1.586, // Standard credit card ratio (approx 85.6mm x 53.98mm)
        borderRadius: 16,
        shadowColor: 'rgba(212, 175, 55, 0.4)', // Subtle gold glow
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
        elevation: 15,
        backgroundColor: '#111',
    },
    cardBg: {
        width: '100%',
        height: '100%',
        padding: 24,
        justifyContent: 'space-between',
    },
    cardImage: {
        borderRadius: 16,
        resizeMode: 'cover',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    brandText: {
        color: '#D4AF37', // Metallic Gold
        fontSize: 18,
        fontWeight: '900',
        letterSpacing: 2,
    },
    cardType: {
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: 10,
        fontWeight: '600',
        letterSpacing: 1,
    },
    chipWrapper: {
        marginTop: 10,
        marginBottom: 10,
    },
    chip: {
        width: 45,
        height: 35,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.5)',
        backgroundColor: 'rgba(212, 175, 55, 0.1)',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
    },
    assetIdText: {
        color: '#D4AF37',
        fontSize: 22,
        fontWeight: '600',
        letterSpacing: 4,
        fontFamily: 'monospace',
        marginBottom: 12,
        textShadowColor: 'rgba(0,0,0,0.8)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    projectInfo: {},
    label: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 1.5,
        marginBottom: 2,
    },
    valueLarge: {
        color: '#FFF',
        fontSize: 24,
        fontWeight: '800',
        letterSpacing: 1,
    },
    projectName: {
        color: 'rgba(212, 175, 55, 0.8)',
        fontSize: 14,
        fontWeight: '600',
        marginTop: 2,
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    footerBlock: {
        flex: 1,
    },
    footerBlockRight: {
        alignItems: 'flex-end',
    },
    valueSmall: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '600',
        letterSpacing: 1,
        fontFamily: 'monospace',
    },
});
